# Generated by Django 4.2.7 on 2023-12-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_botadmin_status_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
