# Generated by Django 4.2.7 on 2023-12-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_question_full_name_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
